name: "[PR] Helm Chart Lint"

on:
  pull_request:
    branches: ['*']
    paths:
      - 'charts/**'
      - '.github/workflows/helm-lint.yml'
jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Lint
        uses: WyriHaximus/github-action-helm3@e3894d973c282349e3d41d3347767f2b2545b583 # v4.0.2
        with:
          exec: helm lint charts/*
